# Generated by Django 5.2.6 on 2025-11-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revibe_app', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='listened_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
