# Generated by Django 5.2.6 on 2025-11-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revibe_app', '0004_journal_listened_to_journal_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='mood',
            field=models.CharField(choices=[('Relaxed', 'Relaxed'), ('Focused', 'Focused'), ('Energetic', 'Energetic'), ('Melancholic', 'Melancholic'), ('Relaxed & Focused', 'Relaxed & Focused'), ('Energetic & Focused', 'Energetic & Focused'), ('Relaxed & Melancholic', 'Relaxed & Melancholic')], max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
