# Generated by Django 5.2.6 on 2025-11-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revibe_app', '0005_alter_playlist_mood_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
